; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
extra_scripts = 
    scripts/copy_files.py
build_unflags = -std=gnu++11
lib_deps = 
    Update
    RF24
    NimBLE-Arduino
    Adafruit GFX Library
    Adafruit SSD1306
    Adafruit BusIO
    GyverButton
    EEPROM
    Wire
    SPI
    WiFi
    DNSServer
    WebServer

[env:128x32_Flexible]
build_src_filter = -<*> +<128x32_Flexible/>
build_flags = 
    -std=gnu++17
    -Wl,-z,muldefs
    -Iinclude/128x32_Flexible

[env:128x64_Flexible]
build_src_filter = -<*> +<128x64_Flexible/>
build_flags = 
    -std=gnu++17
    -Wl,-z,muldefs
    -Iinclude/128x64_Flexible
